/******************************************************************************/
/***          Generated by IBExpert 2008.11.27 4/2/2009 8:38:18 AM          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UNICODE_FSS;

CREATE DATABASE 'protocolvn.info:e:\rdbms\pl-office-prac.GDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UNICODE_FSS;



SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE ST_RPT_DUAN (
    TUNGAY DATE,
    DENNGAY DATE,
    DUAN BIGINT)
RETURNS (
    TONGTHOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    DU_AN VARCHAR(200),
    NHANVIEN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TYPE OF A_DATE_TIME,
    KETHUC TYPE OF A_DATE_TIME,
    THUCHIEN TIME)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE ST_RPT_NGAYLAMVIEC (
    TUNGAY DATE,
    DENNGAY DATE)
RETURNS (
    VETRE INTEGER,
    LAMSOM INTEGER,
    TONGKT INTEGER,
    TONGBD INTEGER,
    GIOKETTHUC TIME,
    GIOBATDAU TIME,
    NGAYLAMVIEC DATE,
    NHANVIEN VARCHAR(200))
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE ST_RPT_NHANVIEN (
    NV_ID BIGINT,
    BAT_DAU DATE,
    KET_THUC DATE)
RETURNS (
    THOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    DUAN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    THUCHIEN TIME,
    NHANVIEN VARCHAR(200))
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE ST_RPT_TIMESHEET
RETURNS (
    NGAYLAMVIEC DATE,
    THUCHIEN TIME,
    DUAN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    NHANVIEN VARCHAR(200))
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE ST_RPT_TONGHOP_TIMESHEET (
    TUNGAY DATE,
    DENNGAY DATE)
RETURNS (
    NGAYLAMVIEC DATE,
    DUAN VARCHAR(200),
    NHANVIEN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    THUCHIEN TIME)
AS
BEGIN
  SUSPEND;
END^


CREATE PROCEDURE ST_TONGHOPTIMESHEET_DUAN (
    DA_ID BIGINT)
RETURNS (
    TONGTHOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    NHANVIEN VARCHAR(200),
    THUCHIEN TIME,
    KETTHUC TIMESTAMP,
    BATDAU TIMESTAMP,
    MOTA VARCHAR(400),
    CONGVIEC VARCHAR(200),
    DUAN VARCHAR(100))
AS
BEGIN
  SUSPEND;
END^



SET TERM ; ^



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CHI_TIET_CONG_VIEC (
    CTCCV_ID             A_BIG_ID NOT NULL,
    DA_ID                A_BIG_ID,
    CV_ID                A_BIG_ID,
    NV_ID                A_BIG_ID,
    MO_TA                VARCHAR(200),
    BAT_DAU              A_DATE_TIME,
    KET_THUC             A_DATE_TIME,
    THOI_GIAN_THUC_HIEN  A_TIME,
    NGAY_LAM_VIEC        A_DATE,
    NGAY_CAP_NHAT        A_DATE_TIME,
    NGUOI_CAP_NHAT       A_BIG_ID,
    DUYET                A_BOOL_NULL,
    NGAY_DUYET           A_DATE_TIME,
    NGUOI_DUYET          A_BIG_ID
);

CREATE TABLE CONG_VIEC (
    ID           BIGINT NOT NULL,
    NAME         VARCHAR(200),
    LOAI_DU_AN   A_BIG_ID,
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE DM_LOAI_DU_AN (
    ID           A_BIG_ID NOT NULL,
    NAME         VARCHAR(100),
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE DU_AN (
    ID           A_BIG_ID NOT NULL,
    NAME         VARCHAR(200) NOT NULL,
    LOAI_DU_AN   A_BIG_ID,
    VISIBLE_BIT  A_BOOL_NULL
);

CREATE TABLE KE_HOACH_LAM_VIEC (
    CTCCV_ID             A_BIG_ID NOT NULL,
    DA_ID                A_BIG_ID,
    CV_ID                A_BIG_ID,
    NV_ID                A_BIG_ID,
    MO_TA                VARCHAR(200),
    BAT_DAU              A_DATE_TIME,
    KET_THUC             A_DATE_TIME,
    THOI_GIAN_THUC_HIEN  A_TIME,
    NGAY_LAM_VIEC        A_DATE,
    NGAY_CAP_NHAT        A_DATE_TIME,
    NGUOI_CAP_NHAT       A_BIG_ID,
    DUYET                A_BOOL_NULL,
    NGAY_DUYET           A_DATE_TIME,
    NGUOI_DUYET          A_BIG_ID
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CHI_TIET_CONG_VIEC ADD CONSTRAINT PK_CHI_TIET_CONG_VIEC PRIMARY KEY (CTCCV_ID);
ALTER TABLE CONG_VIEC ADD CONSTRAINT PK_CONG_VIEC PRIMARY KEY (ID);
ALTER TABLE DM_LOAI_DU_AN ADD CONSTRAINT PK_DM_LOAI_DU_AN PRIMARY KEY (ID);
ALTER TABLE DU_AN ADD CONSTRAINT PK_DU_AN PRIMARY KEY (ID);
ALTER TABLE KE_HOACH_LAM_VIEC ADD CONSTRAINT PK_KE_HOACH_LAM_VIEC PRIMARY KEY (CTCCV_ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CHI_TIET_CONG_VIEC ADD CONSTRAINT FK_CHI_TIET_CONG_VIEC_1 FOREIGN KEY (DA_ID) REFERENCES DU_AN (ID);
ALTER TABLE CHI_TIET_CONG_VIEC ADD CONSTRAINT FK_CHI_TIET_CONG_VIEC_2 FOREIGN KEY (CV_ID) REFERENCES CONG_VIEC (ID);
ALTER TABLE CHI_TIET_CONG_VIEC ADD CONSTRAINT FK_CHI_TIET_CONG_VIEC_3 FOREIGN KEY (NV_ID) REFERENCES DM_NHAN_VIEN (ID);
ALTER TABLE CONG_VIEC ADD CONSTRAINT FK_CONG_VIEC_1 FOREIGN KEY (LOAI_DU_AN) REFERENCES DM_LOAI_DU_AN (ID);
ALTER TABLE DU_AN ADD CONSTRAINT FK_DU_AN_1 FOREIGN KEY (LOAI_DU_AN) REFERENCES DM_LOAI_DU_AN (ID);
ALTER TABLE KE_HOACH_LAM_VIEC ADD CONSTRAINT FK_KE_HOACH_LAM_VIEC_1 FOREIGN KEY (NV_ID) REFERENCES DM_NHAN_VIEN (ID);
ALTER TABLE KE_HOACH_LAM_VIEC ADD CONSTRAINT FK_KE_HOACH_LAM_VIEC_2 FOREIGN KEY (DA_ID) REFERENCES DU_AN (ID);
ALTER TABLE KE_HOACH_LAM_VIEC ADD CONSTRAINT FK_KE_HOACH_LAM_VIEC_3 FOREIGN KEY (CV_ID) REFERENCES CONG_VIEC (ID);


/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE ST_RPT_DUAN (
    TUNGAY DATE,
    DENNGAY DATE,
    DUAN BIGINT)
RETURNS (
    TONGTHOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    DU_AN VARCHAR(200),
    NHANVIEN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TYPE OF A_DATE_TIME,
    KETHUC TYPE OF A_DATE_TIME,
    THUCHIEN TIME)
AS
begin
  for
    select
        b.name as duan,
        e.name as tennhanvien,
        c.name as tencongviec,
        a.mo_ta ,
        a.bat_dau,
        a.ket_thuc,
        a.thoi_gian_thuc_hien,
        a.ngay_lam_viec,
         extract(hour from a.thoi_gian_thuc_hien)*60 + extract(minute from a.thoi_gian_thuc_hien)
    from chi_tiet_cong_viec a, du_an b, cong_viec c, user_cat d, dm_nhan_vien e
    where     a.cv_id = c.id
              and a.da_id = b.id
              and d.employee_id=e.id
              and e.id=a.nv_id
              and   a.da_id= :duan and a.duyet='2'
              and a.ngay_lam_viec between :tungay and :denngay
    into
        :du_an,
        :nhanvien,
        :congviec,
        :mota,
        :batdau,
        :kethuc,
        :thuchien,
        :ngaylamviec,
        :tongthoigian
  do
    begin
      suspend;
    end
end^


ALTER PROCEDURE ST_RPT_NGAYLAMVIEC (
    TUNGAY DATE,
    DENNGAY DATE)
RETURNS (
    VETRE INTEGER,
    LAMSOM INTEGER,
    TONGKT INTEGER,
    TONGBD INTEGER,
    GIOKETTHUC TIME,
    GIOBATDAU TIME,
    NGAYLAMVIEC DATE,
    NHANVIEN VARCHAR(200))
AS
begin
    for
        select
                nv.name,
                cn.ngay_lam_viec,
                cn.gio_bat_dau,
                cn.gio_ket_thuc,
                case when extract(hour from cn.gio_bat_dau) > 12 then (extract(hour from cn.gio_bat_dau)*60 + extract(minute from cn.gio_bat_dau)-(8*60+60)) else (case when (extract(hour from cn.gio_bat_dau)*60 + extract(minute from cn.gio_bat_dau)-8*60)>0 then (extract(hour from cn.gio_bat_dau)*60 + extract(minute from cn.gio_bat_dau)-8*60) else 0 end)  end,
                --case when (extract(hour from cn.gio_bat_dau)*60 + extract(minute from cn.gio_bat_dau)-8*60)>0 then (extract(hour from cn.gio_bat_dau)*60 + extract(minute from cn.gio_bat_dau)-8*60) else 0 end,
               case when extract(hour from cn.gio_ket_thuc) < 12 then (17*60 - 60 - (extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc))) else (case when (extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)-17*60)<0 then 17*60-(extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)) else 0 end ) end,
                case when (extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)-8*60)<0 then 8*60-(extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)) else 0 end ,
                 case when (extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)-17*60)>0 then (extract(hour from cn.gio_ket_thuc)*60 + extract(minute from cn.gio_ket_thuc)-17*60) else 0 end
        from capnhat_ngaylamviec cn,dm_nhan_vien nv
        where cn.nv_id=nv.id and cn.ngay_lam_viec between :tungay and :denngay
        into
            :nhanvien, 
            :ngaylamviec, 
            :giobatdau,
            :gioketthuc,
            :tongbd,
            :tongkt,
            :lamsom,
            :vetre
         do
  begin
  suspend;
  end
end^


ALTER PROCEDURE ST_RPT_NHANVIEN (
    NV_ID BIGINT,
    BAT_DAU DATE,
    KET_THUC DATE)
RETURNS (
    THOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    DUAN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    THUCHIEN TIME,
    NHANVIEN VARCHAR(200))
AS
begin
    for
    select
        b.name,
        c.name,
        a.mo_ta ,
        a.bat_dau,
        a.ket_thuc,
        a.thoi_gian_thuc_hien,
        a.ngay_lam_viec,
        d.name,
        extract(hour from a.thoi_gian_thuc_hien)*60 + extract(minute from a.thoi_gian_thuc_hien)
    from chi_tiet_cong_viec a, du_an b, cong_viec c, dm_nhan_vien d
    where a.cv_id = c.id
        and a.da_id = b.id
        and a.nv_id = d.id
        and a.nv_id = :nv_id and a.duyet='2'
        and a.ngay_lam_viec between :bat_dau and :ket_thuc
    into
     :duan,
     :congviec,
     :mota,
     :batdau,
     :ketthuc,
     :thuchien,
     :ngaylamviec,
     :nhanvien,
     :thoigian
    do
    begin
        suspend;
    end
end^


ALTER PROCEDURE ST_RPT_TIMESHEET
RETURNS (
    NGAYLAMVIEC DATE,
    THUCHIEN TIME,
    DUAN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    NHANVIEN VARCHAR(200))
AS
begin
    for
    select
        b.name,
        c.name,
        a.mo_ta ,
        a.bat_dau,
        a.ket_thuc,
        a.thoi_gian_thuc_hien,
        d.name,
        a.ngay_lam_viec
    from chi_tiet_cong_viec a, du_an b, cong_viec c, dm_nhan_vien d
    where a.cv_id = c.id
        and a.da_id = b.id
        and a.nv_id = d.id
    into
     :duan,
     :congviec,
     :mota,
     :batdau,
     :ketthuc,
     :thuchien,
     :nhanvien,
     :ngaylamviec
    do
    begin
        suspend;
    end
end^


ALTER PROCEDURE ST_RPT_TONGHOP_TIMESHEET (
    TUNGAY DATE,
    DENNGAY DATE)
RETURNS (
    NGAYLAMVIEC DATE,
    DUAN VARCHAR(200),
    NHANVIEN VARCHAR(200),
    CONGVIEC VARCHAR(200),
    MOTA VARCHAR(200),
    BATDAU TIMESTAMP,
    KETTHUC TIMESTAMP,
    THUCHIEN TIME)
AS
begin
    for
    select
        b.name,
        d.name,
        c.name,
        a.mo_ta,
        a.bat_dau,
        a.ket_thuc,
        a.thoi_gian_thuc_hien,
        a.ngay_lam_viec

    from chi_tiet_cong_viec a, du_an b, cong_viec c, dm_nhan_vien d
    where a.cv_id = c.id
        and a.da_id = b.id
        and a.nv_id = d.id
        and  a.ngay_lam_viec between :tungay and :denngay
    into
     :duan,
     :nhanvien,
     :congviec,
     :mota,
     :batdau,
     :ketthuc,
     :thuchien,
     :ngaylamviec
    do
    begin
        suspend;
    end
end^


ALTER PROCEDURE ST_TONGHOPTIMESHEET_DUAN (
    DA_ID BIGINT)
RETURNS (
    TONGTHOIGIAN INTEGER,
    NGAYLAMVIEC DATE,
    NHANVIEN VARCHAR(200),
    THUCHIEN TIME,
    KETTHUC TIMESTAMP,
    BATDAU TIMESTAMP,
    MOTA VARCHAR(400),
    CONGVIEC VARCHAR(200),
    DUAN VARCHAR(100))
AS
begin
    for
    select
        b.name,
        c.name,
        a.mo_ta ,
        a.bat_dau,
        a.ket_thuc,
        a.thoi_gian_thuc_hien,
        d.name,
        a.ngay_lam_viec,
        extract(hour from a.thoi_gian_thuc_hien)*60 + extract(minute from a.thoi_gian_thuc_hien)

    from chi_tiet_cong_viec a, du_an b, cong_viec c, dm_nhan_vien d
    where a.cv_id = c.id
        and a.da_id = b.id
        and a.nv_id = d.id and a.duyet='2' and a.da_id=:da_id
    into
     :duan,
     :congviec,
     :mota,
     :batdau,
     :ketthuc,
     :thuchien,
     :nhanvien,
     :ngaylamviec,
     :tongthoigian

    do
    begin
        suspend;
    end
end^



SET TERM ; ^
